// import type { Metadata } from "next";
// import { Geist, Geist_Mono } from "next/font/google";
// import "./globals.css";

// const geistSans = Geist({
//   variable: "--font-geist-sans",
//   subsets: ["latin"],
// });

// const geistMono = Geist_Mono({
//   variable: "--font-geist-mono",
//   subsets: ["latin"],
// });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

// export default function RootLayout({
//   children,
// }: Readonly<{
//   children: React.ReactNode;
// }>) {
//   return (
//     <html
//       lang="en"
//       className={`${geistSans.variable} ${geistMono.variable} h-full antialiased`}
//     >
//       <body className="min-h-full flex flex-col">{children}</body>
//     </html>
//   );
// }

import type { Metadata } from "next";
import Link from "next/link"; // Import Link for client-side navigation
import "./globals.css";

export const metadata: Metadata = {
  title: "Nagpur Realty Hub | Premium Real Estate",
  description: "Find your dream property in Nagpur. Buy, sell, and invest with trusted experts.",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className="scroll-smooth">
      <body className="antialiased">
        {/* SHARED NAVBAR */}
        <nav className="flex justify-between items-center px-6 md:px-12 py-5 bg-white shadow-sm sticky top-0 z-50">
          
          {/* CLICKABLE LOGO/NAME */}
          <Link 
            href="/" 
            className="font-black text-xl md:text-2xl tracking-tighter text-blue-900 uppercase hover:opacity-80 transition-opacity"
          >
            Nagpur Realty Hub
          </Link>

          {/* NAVIGATION LINKS */}
          <div className="flex space-x-5 md:space-x-8 font-bold text-gray-600 text-sm md:text-base">
            <Link href="/#properties" className="hover:text-blue-700 transition">
              Properties
            </Link>
            <Link href="/#about" className="hover:text-blue-700 transition hidden md:inline-block">
              Services
            </Link>
            <Link href="/privacy" className="hover:text-blue-700 transition">
              Privacy
            </Link>
            <Link 
              href="/#contact" 
              className="bg-blue-900 text-white px-4 py-2 rounded-lg hover:bg-blue-800 transition hidden sm:inline-block text-xs uppercase tracking-wider"
            >
              Inquire
            </Link>
          </div>
        </nav>

        <main>{children}</main>
      </body>
    </html>
  );
}